### PR TITLE
feat: add fix and test for asset handling of imported images

### LINKED ISSUE #498: build / image import broken
an image imported in a server component is missing in the `dist/public/assets` folder.
It exists in the `dist/assets/sample-Xox1zmov.jpg` which is not served by the static server.

Waku Commit: e85380c519a899244c548c460de1d0152efdabbc

```js
import SampleImage from '../assets/sample.jpg';

export const MantineCorePage = async () => {
   return (<img src={SampleImage} />)
}
```

### PR DESCRIPTION
**Pull request by aheissenberger**
This a test case to fix #498

### CODE REVIEW

File: packages/waku/src/lib/builder/build.ts [hunk 1]
```diff
@@ -355,9 +355,10 @@ const buildClientBundle = async (
   ssr: boolean,
 ) => {
   const mainJsFile = joinPath(rootDir, config.srcDir, config.mainJs);
-  const cssAssets = serverBuildOutput.output.flatMap(({ type, fileName }) =>
-    type === 'asset' && fileName.endsWith('.css') ? [fileName] : [],
+  const nonJsAssets = serverBuildOutput.output.flatMap(({ type, fileName }) =>
```
Comment (dai-shi) [inline packages/waku/src/lib/builder/build.ts:358]: Can you please do the same for the SSR bundle? We need it right?

Comment (aheissenberger) [reply packages/waku/src/lib/builder/build.ts:352]: Copying assets to ssr folder is not needed - have a look at my new tests - the leak of "private" JSON assets is tested and works as expected.

Comment (aheissenberger) [reply packages/waku/src/lib/builder/build.ts:352]: @dai-shi can you look at the failed  typescript error - it is not shown when I run `pnpm test` local but I think it is related to the fact that I have changed the `App` component to an async function in `./e2e/fixtures/ssr-target-bundle/src/components/App.tsx` - should I disable the error in `entries.tsx`?

> Type 'Promise<typeof import("/waku/e2e/fixtures/ssr-target-bundle/src/components/App", { with: { "resolution-mode": "import" } })>' is not assignable to type 'Promise<{ default: ComponentType<any>; }>'.

Comment (dai-shi) [reply packages/waku/src/lib/builder/build.ts:352]: > Copying assets to ssr folder is not needed - have a look at my new tests - the leak of "private" JSON assets is tested and works as expected.

Oh, because we don't need styles for SSR? Yeah, that's my oversight.

Comment (aheissenberger) [reply packages/waku/src/lib/builder/build.ts:352]: I have to clarify - the "private" JSON is not leaked to the public directory in your current implementation :-)

**Comment by dai-shi** [comment]
> @dai-shi can you look at the failed typescript error - it is not shown when I run `pnpm test` local but I think it is related to the fact that I have changed the `App` component to an async function in `./e2e/fixtures/ssr-target-bundle/src/components/App.tsx` - should I disable the error in `entries.tsx`?
> 
> > Type 'Promise<typeof import("/waku/e2e/fixtures/ssr-target-bundle/src/components/App", { with: { "resolution-mode": "import" } })>' is not assignable to type 'Promise<{ default: ComponentType; }>'.

`pnpm test` shows the error for me.

**Review by dai-shi — APPROVED** [review]
LGTM. Thanks for your work!
