### PR TITLE
fix: server router

### LINKED ISSUE #417: useLocation not work Error: Missing Router
https://github.com/hyoban/waku-router

When I run `pnpm dev` from a fresh template and add `useLocation`, it works fine.
But when I shut down the dev server and restart it, it doesn't work. Displays `Error: Missing Router`.

```
Error: Missing Router
    at Module.useLocation (file:///Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/waku@0.19.1_react-dom@18.3.0-canary-b30030471-20240117_react-server-dom-webpack@18.3.0-canary_gs5p533tfweocikxyqduoft2v4/node_modules/waku/dist/router/client.js:29:15)
    at Counter (/Users/hyoban/Developer/Demo/waku-router/src/components/counter.tsx:13:42)
    at renderWithHooks (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:9532:16)
    at renderIndeterminateComponent (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:9611:15)
    at renderElement (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:9881:7)
    at renderLazyComponent (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:9858:3)
    at renderElement (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:9977:11)
    at renderNodeDestructive (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:10163:13)
    at retryRenderTask (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:10963:5)
    at retryTask (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:10930:5)
Cannot render RSC Error: Missing Router
    at Module.useLocation (file:///Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/waku@0.19.1_react-dom@18.3.0-canary-b30030471-20240117_react-server-dom-webpack@18.3.0-canary_gs5p533tfweocikxyqduoft2v4/node_modules/waku/dist/router/client.js:29:15)
    at Counter (/Users/hyoban/Developer/Demo/waku-router/src/components/counter.tsx:13:42)
    at renderWithHooks (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:9532:16)
    at renderIndeterminateComponent (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:9611:15)
    at renderElement (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:9881:7)
    at renderLazyComponent (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:9858:3)
    at renderElement (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:9977:11)
    at renderNodeDestructive (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:10163:13)
    at retryRenderTask (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:10963:5)
    at retryTask (/Users/hyoban/Developer/Demo/waku-router/node_modules/.pnpm/react-dom@18.3.0-canary-b30030471-20240117_react@18.3.0-canary-b30030471-20240117/node_modules/react-dom/cjs/react-dom-server.edge.development.js:10930:5)
```

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #417

This PR adds ServerRouter and injects it for the routes in the server, so users don't hit the "Missing router error" 

on Discord: 
> The issue is obvious, useChangeLocation and useLocation are being run in the server (as expected with --with-ssr)
And Router is only wrapped around in main.tsx so this one only runs in the client
Even if we bring it in entries or Layout, it won't work since it uses browser APIs
So the solution is to make Router compatible with being run in the server! Shall I do that?

### CODE REVIEW

**Review by himself65 — COMMENTED** [review]
update test case also?

File: packages/waku/src/lib/renderers/html-renderer.ts [hunk 1]
```diff
@@ -239,13 +240,17 @@ export const renderHtml = async (
       default: { createFromReadableStream },
     },
     { ServerRoot },
+    { ServerRouter },
```
Comment (dai-shi) [inline packages/waku/src/lib/renderers/html-renderer.ts:243]: This is not what we want. **waku/router should work without changing the core.** (otherwise, other router integration like TanStack Router wouldn't be possible.)

You should change `getSsrConfig` in `unstable_defineRouter`. Let me know if you need any help.

File: packages/waku/src/router/client.ts [hunk 2]
```diff
@@ -316,3 +319,34 @@ export function Router() {
...
+  };
+}
+
+export function ServerRouter({
+  children,
+  loc,
+}: PropsWithChildren<{ loc: ReturnType<typeof parseLocation> }>) {
+  if (!isServer) {
+    throw new Error('ServerRouter is not supposed to be run in the client');
+  }
```
Comment (dai-shi) [inline packages/waku/src/router/client.ts:335]: We don't need this check (at least for now). But, maybe we need some comments telling it's not a public API, also for `ServerRoot`.

**Review by dai-shi — CHANGES_REQUESTED** [review]
Good try, but it's not how it's designed. Keep trying.

**Comment by Aslemammad** [comment]
Sure, I'll resolve the comments soon!

**Comment by Aslemammad** [comment]
> update test case also?

Which ones?

File: packages/waku/src/router/client.ts [hunk 3]
```diff
@@ -321,3 +322,34 @@ export function Router() {
...
+}
+
+/**
+ * ServerRouter for SSR
+ * This is not a public API.
+ */
+export function ServerRouter({
+  children,
+  loc,
+}: PropsWithChildren<{ loc: ReturnType<typeof parseLocation> }>) {
```
Comment (dai-shi) [inline packages/waku/src/router/client.ts:339]: Just my preference:
```suggestion
}: { children: ReactNode; loc: ReturnType<typeof parseLocation> }) {
```

Comment (Aslemammad) [reply packages/waku/src/router/client.ts]: I'll revert this since it would force us to pass children and children would force us to have keys if we pass array, unless we pass a fragment, which does not look good too.

Comment (dai-shi) [reply packages/waku/src/router/client.ts]: It's just a TS issue, right?
I can take care of it later.

Comment (Aslemammad) [reply packages/waku/src/router/client.ts]: hmm, ts issue, key issue + code formatting issue

File: package.json [hunk 4]
```diff
@@ -71,9 +71,6 @@
     "eslint-plugin-react-hooks": "^4.6.0",
     "prettier": "^3.2.5",
     "prettier-plugin-tailwindcss": "^0.5.11",
-    "react": "18.3.0-canary-14fd9630e-20240213",
-    "react-dom": "18.3.0-canary-14fd9630e-20240213",
-    "react-server-dom-webpack": "18.3.0-canary-14fd9630e-20240213",
```
Comment (dai-shi) [inline package.json:76]: Was this causing the CI issue?

**Review by dai-shi — APPROVED** [review]
LGTM. Nice work!

**Comment by Aslemammad** [comment]
Yep
