### PR TITLE
fix(use-router): router.push bug

### LINKED ISSUE #1060: useRouter push does not load the given page
### What
When pushing to a page with the hook `useRouter_UNSTABLE`, the page does not load on first try. An explicit `router.reloaded()` is needed to make it work.
It worked fine in waku version `0.21.2`
### How to reproduce
Run the project found [here](https://github.com/pfongkye/waku-use-router) and click on the button "Use router to change page"

### Misc
waku version where issue was detected: `0.21.8`
The code can be found [here](https://github.com/pfongkye/waku-use-router/blob/main/src/pages/index.tsx#L16).

### PR DESCRIPTION
**Pull request by tylersayshi**
fix #1060

### CODE REVIEW

File: e2e/fixtures/use-router/src/pages/dynamic.tsx [hunk 1]
```diff
@@ -1,14 +1,22 @@
-import { Link } from 'waku';
+'use client';
```
Comment (dai-shi) [inline e2e/fixtures/use-router/src/pages/dynamic.tsx:1]: This `/dynamic` page is used for other specs, so it feels safe to avoid changing it to a client component.

**Review by dai-shi — APPROVED** [review]
Let's merge this. If it doesn't solve the issue, we should to the second iteration.
