### PR TITLE
fix: improve resolveClient for DEV

### LINKED ISSUE #982: "Cannot use import statement outside a module" error with dev server
I tried adding `react-error-boundary` to my app and it gives an error with the dev server. I think it works with the production build. I recreated my own ErrorBoundary class component with a "use client" directive by copying from that library and it works in dev mode.

Related to #423. The [`react-error-boundary`](https://github.com/bvaughn/react-error-boundary) package is still recommended in the React 19 docs at the bottom of this section and in some other code examples https://19.react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary

To reproduce, create a waku app, add `react-error-boundary` dependency, import and use it somewhere (like App.tsx)

```ts
import { ErrorBoundary } from 'react-error-boundary';
```

```tsx
<ErrorBoundary fallback={<div>Something went wrong!</div>}>
  <ComponentsThatMightFail />
</ErrorBoundary>
```

Here is the error:

```
node_modules/react-error-boundary/dist/react-error-boundary.development.esm.js:2
import { createContext, Component, createElement, isValidElement, useContext, useState, useMemo, forwardRef } from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1383:18)
    at Module._compile (node:internal/modules/cjs/loader:1412:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at cjsLoader (node:internal/modules/esm/translators:318:5)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:258:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:485:26)
```

### PR DESCRIPTION
**Pull request by dai-shi**
close #982

### CODE REVIEW

File: packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts [hunk 1]
```diff
@@ -648,35 +670,58 @@ export function rscTransformPlugin(
...
+      if (id.startsWith('/@id/')) {
+        return (await this.resolve(id.slice('/@id/'.length), importer, options))
+          ?.id;
       }
-      if (!EXTENSIONS.includes(extname(id))) {
+      const resolved = await this.resolve(id, importer, options);
+      let srcId =
+        importer && (id.startsWith('./') || id.startsWith('../'))
+          ? joinPath('/@fs', importer.split('?')[0]!, '..', id)
+          : id;
```
Comment (himself65) [inline packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts:692]: this might be the issue

**Comment by dai-shi** [comment]
e2e tests take longer and longer. We need to consider something eventually.
