### PR TITLE
fix: private dir hmr

### LINKED ISSUE #592: support listening to private directory for changes and trigger RSC hot reload
Right now changes to `./private` files requires a manual refresh to load the latest data in local development.

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #592 

We did not react to changes in the private dir. 

Since we're sure they're server only, let's treat them as rsc updates, so the changes get reflected on the client.

### CODE REVIEW

File: packages/waku/src/lib/renderers/dev-worker-impl.ts [hunk 1]
```diff
@@ -168,20 +169,21 @@ const handleGetSsrConfig = async (
 
 const dummyServer = new Server(); // FIXME we hope to avoid this hack
 
+const hotUpdateCallback = (payload: HotUpdatePayload) => {
+  const mesg: MessageRes = { type: 'hot-update', payload };
+  parentPort!.postMessage(mesg);
+};
```
Comment (dai-shi) [inline packages/waku/src/lib/renderers/dev-worker-impl.ts:175]:
```suggestion
};

```

**Review by dai-shi — APPROVED** [review]
LGTM!
