### PR TITLE
fix: client components default exports

### LINKED ISSUE #434: Error: Element type is invalid. Received a promise that resolves to: undefined. Lazy element type must resolve to a class or function.
hi there 
i was just exploring waku and i got  an error when i tried to import client component into server component here is my code 

```jsx
"use client";
function SubmitButton({ addTodo }: { addTodo: () => void }) {
  return (
    <div>
      <button onClick={() => addTodo()} type="button">
        add
      </button>
    </div>
  );
}

export default SubmitButton;

```

```js 

"use server";
import { type RenderContext } from "waku/server";
export const todos: Array<{ name: string; completed: boolean }> = [
  { name: "initial todo", completed: false },
];

addTodo const addTodo = (ctx: RenderContext) => {
  todos.push({name : 'new todo", completed:false})
  ctx.rerender("waku");
};
```

```jsx
import { addTodo, todos } from "./actions.js";
import SubmitButton from "./submitButton.js";

export const Todos = () => {
  return (
    <section className="border-blue-400 -mx-4 mt-4 rounded border border-dashed p-4">
      <div>
        {todos.map(({ name, completed }) => {
          return (
            <div>
              {name} <input type="checkbox" defaultChecked={completed} />
            </div>
          );
        })}
      </div>
      <input type="text" name="name" />
      <SubmitButton addTodo={addTodo} />
    </section>
  );
};

```
Upon running this code, I receive the error: "Element type is invalid. Received a promise that resolves to: undefined. Lazy element type must resolve to a class or function.

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #434 

TIL: 
```ts
export * from 'url'
```
does not re-export the `default` export.

### CODE REVIEW

File: packages/waku/src/lib/handlers/handler-dev.ts [hunk 1]
```diff
@@ -228,9 +228,15 @@ export function createHandler<
         item.url !== viteUrl &&
         !item.url.includes('?html-proxy')
       ) {
+        const { code } = (await vite.transformRequest(item.url))!;
         res.setHeader('Content-Type', 'application/javascript');
         res.setStatus(200);
-        endStream(res.stream, `export * from "${item.url}";`);
```
Comment (dai-shi) [inline packages/waku/src/lib/handlers/handler-dev.ts:233]: It might not follow ESM, but does this cause an error?
```ts
endStream(res.stream, `export * from "${item.url}"; export { default } from "${item.url}";`);
```

Comment (Aslemammad) [reply packages/waku/src/lib/handlers/handler-dev.ts:233]: Yep, I haven't tried it, but the reason I guess is that the default export does not exist in many cases.

Comment (Aslemammad) [reply packages/waku/src/lib/handlers/handler-dev.ts:233]: And exporting what is not exported would cause an error I assume.

Comment (dai-shi) [reply packages/waku/src/lib/handlers/handler-dev.ts:233]: yeah, that's what I've concerned. If you tried it, it's good.

File: packages/waku/src/lib/handlers/handler-dev.ts [hunk 2]
```diff
@@ -228,9 +228,15 @@ export function createHandler<
         item.url !== viteUrl &&
         !item.url.includes('?html-proxy')
       ) {
+        const { code } = (await vite.transformRequest(item.url))!;
```
Comment (dai-shi) [inline packages/waku/src/lib/handlers/handler-dev.ts:231]: I personally didn't like my hack from L218, and this makes me concerned more.
Let's look for a better solution (I'll open a new issue), and merge this as a temporary workaround for now.

**Review by dai-shi — APPROVED** [review]
