### PR TITLE
Fix response streaming with wrangler dev server

### LINKED ISSUE #1237: Streaming dynamic server responses are buffered when testing with `wrangler dev`
It doesn't happen in production with a Cloudflare Worker or with `waku dev`. I found a [related issue](https://github.com/cloudflare/workers-sdk/issues/8004) in the workers-sdk repo. It seems to be due to automatic compression of html and txt responses. It looks like there is a [workaround](https://github.com/cloudflare/workers-sdk/issues/6577#issuecomment-2387260894) - but I think we can wait for an upstream fix to [#8004](https://github.com/cloudflare/workers-sdk/issues/8004).

### PR DESCRIPTION
**Pull request by rmarscher**
Fixes #1237.

### CODE REVIEW

File: examples/07_cloudflare/waku.cloudflare-middleware.ts [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+export type HandlerRes = {
+  body?: ReadableStream;
+  headers?: Record<string, string | string[]>;
+  status?: number;
+};
+export type HandlerContext = {
+  readonly req: HandlerReq;
+  readonly res: HandlerRes;
+  readonly context: Record<string, unknown>;
+};
```
Comment (rmarscher) [inline examples/07_cloudflare/waku.cloudflare-middleware.ts:20]: Can we export this from waku? I think only the Middleware type is exported from `'waku/config'` and I don't see a way to extract HandlerContext.

File: examples/07_cloudflare/src/lib/hono.ts [hunk 2]
```diff
@@ -1,12 +1,12 @@
-import { getHonoContext as getHonoContextFromWaku } from 'waku/unstable_hono';
+import { getHonoContext as _getHonoContext } from 'waku/unstable_hono';
```
Comment (dai-shi) [inline examples/07_cloudflare/src/lib/hono.ts:1]: It's our coding style to use `_` prefix for "unused values", so we want to avoid using `_` for other meanings.

File: examples/07_cloudflare/waku.cloudflare-middleware.ts (hunk 1 above)
Comment (dai-shi) [reply examples/07_cloudflare/waku.cloudflare-middleware.ts:20]: I'll consider it in the future, but not soon.

Meanwhile:
```ts
type HandlerContext = Parameters<ReturnType<Middleware>>[0];
```

Comment (rmarscher) [reply examples/07_cloudflare/waku.cloudflare-middleware.ts:20]: Thanks. I don't think I've used `<Parameters>` before. Good to know.

**Comment by rmarscher** [comment]
Thanks for the review @dai-shi. I resolved the comments.

**Review by dai-shi — APPROVED** [review]
It looks pretty hacky, but I assume it's unavoidable.
